name: Build and Release Tauri App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug the runner OS
        run: echo "Running on ${{ runner.os }}"

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npm install tailwindcss-animate

      - name: Run npm audit
        run: npm audit --audit-level=high

      - name: Install GTK and Build Tools (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev build-essential pkg-config

      - name: Install Tauri CLI (locally)
        run: npm install @tauri-apps/cli

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Build Tauri App
        run: npx tauri build

      # Upload platform-specific artifacts
      - name: Upload Artifact for macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-macos
          path: src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload Artifact for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/bundle/msi/*.msi

      - name: Upload Artifact for Linux (deb)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-linux-deb
          path: src-tauri/target/release/bundle/deb/*.deb

      - name: Upload Artifact for Linux (rpm)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: tauri-app-linux-rpm
          path: src-tauri/target/release/bundle/rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch All Tags
        run: git fetch --tags

      - name: Verify Created Tag
        run: |
          echo "Verifying tag ${{ github.ref }}"
          if ! git tag -l | grep -q "${{ github.ref }}"; then
            echo "Error: Tag ${{ github.ref }} not found locally."
            exit 1
          fi

      # Download platform-specific artifacts
      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: tauri-app-macos
          path: src-tauri/target/release/bundle/dmg

      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/bundle/msi

      - name: Download Linux Artifact (deb)
        uses: actions/download-artifact@v3
        with:
          name: tauri-app-linux-deb
          path: src-tauri/target/release/bundle/deb

      - name: Download Linux Artifact (rpm)
        uses: actions/download-artifact@v3
        with:
          name: tauri-app-linux-rpm
          path: src-tauri/target/release/bundle/rpm

      # Create GitHub Release with only artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
