name: Build Tauri App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Debug the runner OS
        run: echo "Running on ${{ runner.os }}"


      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install
          npm install tailwindcss-animate

      - name: Install dependencies for sharp (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install vips

      - name: Install GDK and GTK dependencies (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev pkg-config
          sudo apt-get install -y libgdk-3.0-dev

      - name: Set PKG_CONFIG_PATH (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          # Set PKG_CONFIG_PATH to the directory containing gdk-3.0.pc
          echo "/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "/usr/local/lib/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH set to: $PKG_CONFIG_PATH"

      - name: Install Tauri CLI (locally)
        run: npm install @tauri-apps/cli

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Build Tauri App
        run: npx tauri build  # Use npx to run locally installed Tauri

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-tauri-app
          path: src-tauri/target/release/bundle/
